name = "d1-hono-suzuya"
main = "src/index.ts"
compatibility_date = "2023-12-21"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "suzuyatest"
database_id = "603d21f2-38da-4529-ab7e-20fb7d3ec22c"
